"""Shared configuration constants for the nightlight TUI and control script."""

from pathlib import Path

HOME = Path.home()

SCRIPT = HOME / ".config/waybar/scripts/nightlight.sh"
BASE_DIR = HOME / ".config/waybar/nightlight"
CONSTANTS_FILE = BASE_DIR / "constants.env"

STATE_FILE = BASE_DIR / "state"
TEMP_FILE = BASE_DIR / "temp"
SCHEDULE_FILE = BASE_DIR / "schedule_enabled"
START_FILE = BASE_DIR / "start"
END_FILE = BASE_DIR / "end"

MIN_TEMP = 2500
MAX_TEMP = 6500
DEFAULT_TEMP = 4000
OFF_TEMP = 6000
TEMP_STEP = 250

DEFAULT_STATE = "off"
DEFAULT_SCHEDULE = "off"
DEFAULT_START = "20:00"
DEFAULT_END = "07:00"

PRESET_OPTIONS: list[tuple[str, str]] = [
    ("5000K - Suave", "5000"),
    ("4000K - Normal de noche", "4000"),
    ("3500K - Cálido", "3500"),
    ("3000K - Muy naranja", "3000"),
    ("2500K - Extremo", "2500"),
]

PRESET_TEMPS = [int(value) for _, value in PRESET_OPTIONS]

ASCII_SUN_LENS = """
    \\   |   /
  .-- [☀] --.
 /     |     \\
      (___)
  ┌───────────┐
  │  ○     ○  │
  └───────────┘
  Luz diurna"""

ASCII_MOON_LENS = """
      .-----.
    ,'   ☾   `.
   /    ___    \\
       (   )
  ┌───────────┐
  │  ◐     ◑  │
  └───────────┘
  Luz nocturna"""

CSS_PATH = Path(__file__).with_name("styles.tcss")

SYSTEMD_SERVICE = "nightlight-schedule.service"
SYSTEMD_TIMER = "nightlight-schedule.timer"

FILE_DEFAULTS: dict[Path, str] = {
    STATE_FILE: DEFAULT_STATE,
    TEMP_FILE: str(DEFAULT_TEMP),
    SCHEDULE_FILE: DEFAULT_SCHEDULE,
    START_FILE: DEFAULT_START,
    END_FILE: DEFAULT_END,
}


def constants_env_content() -> str:
    """Generate constants.env content shared with nightlight.sh."""
    return f"""# Auto-generated by nightlight-tui. Do not edit manually.
MIN_TEMP={MIN_TEMP}
MAX_TEMP={MAX_TEMP}
DEFAULT_TEMP={DEFAULT_TEMP}
OFF_TEMP={OFF_TEMP}
TEMP_STEP={TEMP_STEP}
"""
